window.background.image.scale=true
window.transparency=1
text.font.name.global.enable=false
window.split.weight=659
window.always.top=false
window.theme=深色
window.title.menu=true
window.background.image.alpha=0.8
quick.key.menu.type.setting=ctrlz
window.image.enable=true
window.absorb=true
baidu.ocr.secret.key=qrenc:257f8d4a0600b141879c0abd88318083999edcb7c3629ad72a26ece6b3d9ed55b743144bf1d0b725
window.round=true
baidu.ocr.api.key=qrenc:1ae4eae3cc6360334491594bd635ec55f882f746d737d1a3b743144bf1d0b725
ocr.provider=baidu
selected.file.directory=/home/kiarelemb/IdeaProjects/QR_Scan_Grade/res